name: Release stage 1 - create release PR (Cylc 8+ only)

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number (PEP 440 compliant e.g., 8.12.4, 8.0a2 etc)
        required: true
      branch:
        description: The branch to open the PR against
        required: false
        default: 'master'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Sanitise workflow inputs # Should be 1st step
        uses: MetRonnie/release-actions/stage-1/sanitize-inputs@badges

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BASE_REF }}
          fetch-depth: 0  # need to fetch all commits to check contributors

      - name: Check CONTRIBUTING.md
        uses: MetRonnie/release-actions/check-shortlog@badges

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Create & checkout PR branch
        uses: MetRonnie/release-actions/stage-1/checkout-pr-branch@badges

      - name: Set the package version
        uses: MetRonnie/release-actions/stage-1/set-python-package-version@badges
        with:
          init-file: 'cylc/flow/__init__.py'
          pypi-package-name: 'cylc-flow'

      - name: Update "released on" date in changelog
        continue-on-error: true
        uses: MetRonnie/release-actions/stage-1/update-changelog-release-date@badges
        with:
          changelog-file: 'CHANGES.md'

      - name: Test build
        uses: MetRonnie/release-actions/build-python-package@badges

      - name: Create pull request
        uses: MetRonnie/release-actions/stage-1/create-release-pr@badges
        with:
          message: (Testing)
          gh-actions-workflows: test_fast.yml, test_functional.yml, bash.yml, test_manylinux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
