name: fast tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - '8.*.x'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -c "exec $CONDA_PREFIX/bin/bash -elo pipefail {0}"

env:
  PIP_PROGRESS_BAR: off

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false # don't stop on first failure
      matrix:
        os: ['macos-latest']
        python-version: ['3.8', '3']
    env:
      TZ: ${{ matrix.time-zone }}
      PYTEST_ADDOPTS: --cov --cov-append -n 5 --color=yes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install System Dependencies
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          post-cleanup: 'all'
          environment-name: cylc-fast-test
          create-args: >-
            python=${{ matrix.python-version }}
            pip
            bash
            subversion
            sqlite

      - name: Install Python Dependencies
        run: |
          pip install -e ."[all]"

      - name: Configure git  # Needed by the odd test
        uses: cylc/release-actions/configure-git@v1

      - run: cat /etc/hosts

      - name: Muldoon
        shell: /Users/runner/micromamba/envs/cylc-fast-test/bin/python {0}
        continue-on-error: true
        run: |
          import socket
          print(socket.gethostname())
          print("OK")
          print(socket.getfqdn('localhost'))

      - name: Nedry
        shell: /Users/runner/micromamba/envs/cylc-fast-test/bin/python {0}
        continue-on-error: true
        run: |
          import socket
          print(socket.gethostbyname_ex(socket.gethostname()))
          print("OK")
          print(socket.gethostbyname_ex("localhost"))
          print("OK")
          print(socket.gethostbyname_ex(socket.getfqdn('localhost')))

      - name: Dodgson
        shell: /Users/runner/micromamba/envs/cylc-fast-test/bin/python {0}
        continue-on-error: true
        run: |
          import socket
          print(socket.gethostbyaddr('127.0.0.1'))
          print("OK")
          print(socket.gethostbyaddr('localhost'))

      - continue-on-error: true
        run: pytest tests/unit/test_host_select.py

      - continue-on-error: true
        run: pytest tests/unit/test_host_select_remote.py

      - continue-on-error: true
        run: pytest tests/unit/test_hostuserutil.py
