name: fast tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - '8.*.x'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -c "exec $CONDA_PREFIX/bin/bash -elo pipefail {0}"

env:
  PIP_PROGRESS_BAR: off

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false # don't stop on first failure
      matrix:
        os: ['macos-15', 'macos-14', 'macos-13']
        python-version: ['3']
    env:
      TZ: ${{ matrix.time-zone }}
      PYTEST_ADDOPTS: --cov --cov-append -n 5 --color=yes
    steps:
      - name: Install System Dependencies
        uses: mamba-org/setup-micromamba@v2
        with:
          post-cleanup: 'all'
          environment-name: cylc-fast-test
          create-args: >-
            python=${{ matrix.python-version }}

      - run: cat /etc/hosts

      - name: Muldoon
        shell: /Users/runner/micromamba/envs/cylc-fast-test/bin/python {0}
        continue-on-error: true
        run: |
          import socket
          this_fqdn = socket.getfqdn()
          print(f"FQDN: {this_fqdn}")
          this_hostname = this_fqdn.split('.')[0]
          print(f"hostname: {socket.gethostname()}")
          this_ip = socket.gethostbyname(this_fqdn)
          print(f"IP: {this_ip}")
          localhost_ip = socket.gethostbyname('localhost')
          print(f"localhost IP: {localhost_ip}")

          print("")

          for func in [
            socket.getfqdn,
            socket.gethostbyaddr,
            socket.gethostbyname_ex,
          ]:
            for x in [
              this_fqdn,
              this_hostname,
              this_ip,
              "localhost",
              "LOCALHOST",
              "localhost4.localdomain4",
              "127.0.0.1",
              "::1",
              "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa",
              "1.0.0.127.in-addr.arpa",
              "muldoon",
            ]:
              print(f"Testing {func.__name__}({x!r})")
              try:
                print(func(x))
              except IOError as e:
                print(f"{type(e).__name__}: {e}")
              print("")
